library(faraway)
data(state)
statedata <- data.frame(state.x77,row.names=state.abb)
g <- lm(Life.Exp ~ ., data=statedata)
summary(g)
g <- update(g, . ~ . - Area)
summary(g)
g <- update(g, . ~ . - Illiteracy)
summary(g)
g <- update(g, . ~ . - Income)
summary(g)
g <- update(g, . ~ . - Population)
summary(g)
summary(lm(Life.Exp ~ Illiteracy+Murder+Frost, statedata))
g <- lm(Life.Exp ~ ., data=statedata)
step(g)
library(leaps)
b<-regsubsets(Life.Exp~.,data=statedata)
(rs <- summary(b))
plot(2:8,rs$cp,xlab="No. of Parameters",ylab="Cp Statistic")
abline(0,1)
plot(2:8,rs$adjr2,xlab="No. of Parameters",ylab="Adjusted R-square")
h <- lm.influence(g)$hat
names(h) <- state.abb
rev(sort(h))
b<-regsubsets(Life.Exp~.,data=statedata,subset=(state.abb!="AK"))
rs <- summary(b)
rs$which[which.max(rs$adjr),]
stripchart(data.frame(scale(statedata)),vertical=TRUE,method="jitter")
b<-regsubsets(Life.Exp~log(Population)+Income+Illiteracy+Murder+HS.Grad+Frost+log(Area),statedata)
rs <- summary(b)
rs$which[which.max(rs$adjr),]
