library(faraway)
x <- seq(0,8,by=0.1)
plot(x,dgamma(x,0.75),type="l",ylab="",xlab="",ylim=c(0,1.25),xaxs="i",yaxs="i")
plot(x,dgamma(x,1.0),type="l",ylab="",xlab="",ylim=c(0,1.25),xaxs="i",yaxs="i")
plot(x,dgamma(x,2.0),type="l",ylab="",xlab="",ylim=c(0,1.25),xaxs="i",yaxs="i")
data(wafer)
summary(wafer)
llmdl <- lm(log(resist) ~ .^2, wafer)
rlmdl <- step(llmdl)
summary(rlmdl)
gmdl <- glm(resist ~ .^2, family=Gamma(link=log), wafer)
rgmdl <- step(gmdl)
summary(rgmdl)
sqrt(0.0045249)
library(MASS)
gamma.dispersion(rgmdl)
data(motorins)
motori <- motorins[motorins$Zone == 1,]
gl <- glm(Payment ~ offset(log(Insured))+as.numeric(Kilometres)+Make+Bonus , family=Gamma(link=log), motori)
summary(gl)
llg <- glm(log(Payment) ~ offset(log(Insured))+as.numeric(Kilometres)+Make+Bonus,family=gaussian ,  motori)
summary(llg)
x <- seq(0,5,by=0.05)
plot(x,dgamma(x,1/0.55597,scale=0.55597),type="l",ylab="",xlab="",yaxs="i",ylim=c(0,1))
plot(x,dlnorm(x,meanlog=-0.30551,sdlog=sqrt(0.61102)),type="l",ylab="",xlab="",yaxs="i",ylim=c(0,1))
x0 <- data.frame(Make="1",Kilometres=1,Bonus=1,Insured=100)
predict(gl,new=x0,se=T,type="response")
predict(llg,new=x0,se=T,type="response")
c(exp(10.998),exp(10.998)*0.16145)
library(SuppDists)
x <- seq(0,8,by=0.1)
plot(x,dinvGauss(x,1,0.5),type="l",ylab="",xlab="",ylim=c(0,1.5),xaxs="i",yaxs="i")
plot(x,dinvGauss(x,1,1),type="l",ylab="",xlab="",ylim=c(0,1.5),xaxs="i",yaxs="i")
plot(x,dinvGauss(x,1,5),type="l",ylab="",xlab="",ylim=c(0,1.5),xaxs="i",yaxs="i")
data(cpd)
lmod <- lm(actual ~ projected-1,cpd)
summary(lmod)
plot(actual ~ projected, cpd)
abline(lmod)
igmod <- glm(actual ~ projected-1, family=inverse.gaussian(link="identity"), cpd)
summary(igmod)
abline(igmod,lty=2)
plot(residuals(igmod) ~ log(fitted(igmod)),ylab="Deviance residuals",xlab=expression(log(hat(mu))))
abline(h=0)
data(weldstrength)
lmod <- lm(Strength ~ Drying + Material + Preheating, weldstrength)
summary(lmod)
h <- influence(lmod)$hat
d <- residuals(lmod)^2/(1-h)
gmod <- glm(d ~ Material+Preheating,family=Gamma(link=log),weldstrength,weights=1-h)
w <- 1/fitted(gmod)
lmod <- lm(Strength ~ Drying + Material + Preheating, weldstrength, weights=w)
summary(lmod)
summary(gmod)
data(mammalsleep)
mammalsleep$pdr <- with(mammalsleep, dream/sleep)
summary(mammalsleep$pdr)
modl <- glm(pdr ~ log(body)+log(brain)+log(lifespan)+log(gestation)+predation+exposure+danger, family=quasibinomial, mammalsleep)
drop1(modl,test="F")
modl <- glm(pdr ~ log(body)+log(lifespan)+danger, family=quasibinomial, mammalsleep )
summary(modl)
ll <- row.names(na.omit(mammalsleep[,c(1,6,10,11)]))
halfnorm(cooks.distance(modl),labs=ll)
plot(predict(modl),residuals(modl,type="pearson"),xlab="Linear Predictor", ylab="Pearson Residuals")
