library(faraway)
data(gala)
gala <- gala[,-2]
modl <- lm(Species ~ . , gala)
plot(predict(modl),residuals(modl),xlab="Fitted",ylab="Residuals")
modt <- lm(sqrt(Species) ~ . , gala)
plot(predict(modt),residuals(modt),xlab="Fitted",ylab="Residuals")
summary(modt)
modp <- glm(Species ~ .,family=poisson,gala)
summary(modp)
halfnorm(residuals(modp))
plot(log(fitted(modp)),log((gala$Species-fitted(modp))^2),xlab=expression(hat(mu)),ylab=expression((y-hat(mu))^2))
abline(0,1)
(dp <- sum(residuals(modp,type="pearson")^2)/modp$df.res)
summary(modp,dispersion=dp)
drop1(modp,test="F")
data(dicentric)
round(xtabs(ca/cells ~ doseamt+doserate, dicentric),2)
with(dicentric,interaction.plot(doseamt,doserate,ca/cells))
lmod <- lm(ca/cells ~ log(doserate)*factor(doseamt), dicentric)
summary(lmod)$adj
plot(residuals(lmod) ~ fitted(lmod),xlab="Fitted",ylab="Residuals")
abline(h=0)
dicentric$dosef <- factor(dicentric$doseamt)
pmod <- glm(ca ~ log(cells)+log(doserate)*dosef, family=poisson,dicentric)
summary(pmod)
rmod <- glm(ca ~ offset(log(cells))+log(doserate)*dosef, family=poisson,dicentric)
summary(rmod)
data(solder)
modp <- glm(skips ~ . , family=poisson, data=solder)
deviance(modp)
df.residual(modp)
modp2  <- glm(skips ~ (Opening +Solder + Mask + PadType + Panel)^2 , family=poisson, data=solder)
deviance(modp2)
pchisq(deviance(modp2),df.residual(modp2),lower=FALSE)
library(MASS)
modn <- glm(skips ~ .,negative.binomial(1),solder)
modn
modn <- glm.nb(skips ~ .,solder)
summary(modn)
