library(faraway)
data(psid)
head(psid)
library(lattice)
xyplot(income ~ year | person, psid, type="l", subset=(person < 21),strip=FALSE)
xyplot(log(income+100) ~ year | sex, psid, type="l")
lmod <- lm(log(income) ~ I(year-78), subset=(person==1), psid)
coef(lmod)
slopes <- numeric(85);intercepts <- numeric(85)
for(i in 1:85){
lmod <- lm(log(income) ~ I(year-78), subset=(person==i), psid)
intercepts[i] <- coef(lmod)[1]
slopes[i] <- coef(lmod)[2]
}
plot(intercepts,slopes,xlab="Intercept",ylab="Slope")
psex <- psid$sex[match(1:85,psid$person)]
boxplot(split(slopes,psex))
t.test(slopes[psex=="M"],slopes[psex=="F"])
t.test(intercepts[psex=="M"],intercepts[psex=="F"])
library(lme4)
psid$cyear <- psid$year-78
mmod <- lmer(log(income) ~ cyear*sex +age+educ+(cyear|person),psid)
summary(mmod)
qqmath(~resid(mmod) | sex, psid)
xyplot(resid(mmod) ~ fitted(mmod) | cut(educ,c(0,8.5,12.5,20)), psid, layout=c(3,1),xlab="Fitted",ylab="Residuals")
data(vision)
vision$npower <- rep(1:4,14)
xyplot(acuity~npower|subject,vision,type="l",groups=eye,lty=1:2,layout=c(4,2))
mmod <- lmer(acuity~power+(1|subject)+(1|subject:eye),vision)
summary(mmod)
4.64^2/(4.64^2+3.21^2+4.07^2)
(4.64^2+3.21^2)/(4.64^2+3.21^2+4.07^2)
anova(mmod)
mmodr <- lmer(acuity~power+(1|subject)+(1|subject:eye),vision,subset=-43)
anova(mmodr)
summary(mmodr)
op <- options(contrasts=c("contr.helmert", "contr.poly"))
mmodr <- lmer(acuity~power+(1|subject)+(1|subject:eye),vision,subset=-43)
summary(mmodr)
options(op)
contr.helmert(4)
plot(resid(mmodr) ~ fitted(mmodr),xlab="Fitted",ylab="Residuals")
abline(h=0)
qqnorm(ranef(mmodr)$"subject:eye"[[1]],main="")
data(jsp)
jspr <- jsp[jsp$year==2,]
mjspr <- data.frame(rbind(jspr[,1:6],jspr[,1:6]),subject=factor(rep(c("english","math"),c(953,953))),score=c(jspr$english/100,jspr$math/40))
xyplot(score ~ raven| subject*gender, mjspr)
mjspr$craven <- mjspr$raven-mean(mjspr$raven)
mmod <- lmer(score ~ subject*gender+craven*subject+social+(1|school)+(1|school:class)+(1|school:class:id),mjspr)
anova(mmod)
summary(mmod)
0.1013^2/(0.1013^2+0.1166^2)
xyplot(residuals(mmod) ~ fitted(mmod)|subject,mjspr,pch=".",xlab="Fitted",ylab="Residuals")
